### ISSUE TITLE
Sharing and footer buttons

### ISSUE THREAD

**Issue by adolphenom** [curiositry/mnml-ghost-theme#27]
Hi!

I noticed something more in the theme. Could it be possible to add more sharing buttons? I mean, LinkedIn, Reddit, Tumblr, maybe Pocket and Pinterest too.

And, another thing. I don't know how to add more buttons at the footer. I tried, but I couldn't. Could you explain this, please?

I try to help you with the Wiki about all that stuff, so people go there and see the information :)

Thank you for your attention!

**Comment by omphalosskeptic** [comment]
Yes, more sharing buttons can be added. You’d need to either add matching icons, or use whatever default images they use. I’m planning to re-arrange where the sharing buttons are located in the next update, as there isn’t much room for them at the moment. What specific ones would you need? 

(On a similar note, I read a [few](https://ia.net/know-how/sweep-the-sleaze) [articles](http://solomon.io/why-im-done-with-social-media-buttons/) about sharing buttons, and I’ll probably remove them from my blog …)

Regarding links in the footer: on line ~38 of default.hbs is `{{!>navigation-links}}`. To activate footer links, replace that line with `{{>navigation-links}}`. Then, edit `partials/navigation-links.hbs` with whatever links you want (by default it’s home/about/contact)

Does this answer your questions?

**Comment by adolphenom** [comment]
Am... LoL dude! Well, I think you can make a .hbs file with share buttons
and (dis)comment whenever you need them (like footer's links, for example).
Also I don't like them so much, but if there's the posibility to do that,
maybe other people will be thankful :)

About the second part, no, sorry, it doesn't. What I mean is that:
http://i.imgur.com/PPDEMhY.png. I mean if it could be possible to add more
buttons there, at left or right of the RSS' button. I tried, but I didn't
get good results :(

On 24 January 2015 at 21:09, Omphalosskeptic <notifications@github.com>
wrote:

> Yes, more sharing buttons can be added. You’d need to either add matching
> icons, or use whatever default images they use. I’m planning to re-arrange
> where the sharing buttons are located in the next update, as there isn’t
> much room for them at the moment. What specific ones would you need?
>
> (On a similar note, I read a few
> <https://ia.net/know-how/sweep-the-sleaze> articles
> <http://solomon.io/why-im-done-with-social-media-buttons/> about sharing
> buttons, and I’ll probably remove them from my blog …)
>
> Regarding links in the footer: on line ~38 of default.hbs is
> {{!>navigation-links}}. To activate footer links, replace that line with
> {{>navigation-links}}. Then, edit partials/navigation-links.hbs with
> whatever links you want (by default it’s home/about/contact)
>
> Does this answer your questions?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/omphalosskeptic/mnml-ghost-theme/issues/27#issuecomment-71335050>
> .
>



-- 
*adolfo santiago *
*adol.pw <http://adol.pw>*

**Comment by omphalosskeptic** [comment]
Unfortunatly, the RSS button has a lot of specific postioning to get it in the right place, to it’s not easy to add more buttons along side it. If you want yo get into the CSS, you could duplicate it, and then add another class and position it next to the RSS button, but the theme’s not set up to be able to have multiple buttons there.

I’m working on some big upgrades for the theme, and the share and RSS buttons are going to be re-arranged when I do that, so I’ll put them in a partial and try to make it easier to add other sharing channels.

(Alternately, there’s SumoMe’s sharing widget, which is easy to add to a site and appearently works well; you could add it to your blog to get more sharing options while I work on the theme: http://sumome.com/app/share)

**Comment by adolphenom** [comment]
I'm going to wait for what you said and see the new changes you're going to
make.

You can close this issue. Thank you for replying me :-).

On 29 January 2015 at 05:02, Omphalosskeptic <notifications@github.com>
wrote:

> Unfortunatly, the RSS button has a lot of specific postioning to get it in
> the right place, to it’s not easy to add more buttons along side it. If you
> want yo get into the CSS, you could duplicate it, and then add another
> class and position it next to the RSS button, but the theme’s not set up to
> be able to have multiple buttons there.
>
> I’m working on some big upgrades for the theme, and the share and RSS
> buttons are going to be re-arranged when I do that, so I’ll put them in a
> partial and try to make it easier to add other sharing channels.
>
> (Alternately, there’s SumoMe’s sharing widget, which is easy to add to a
> site and appearently works well; you could add it to your blog to get more
> sharing options while I work on the theme: http://sumome.com/app/share)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/omphalosskeptic/mnml-ghost-theme/issues/27#issuecomment-71965633>
> .
>



-- 
*adolfo santiago *
*adol.pw <http://adol.pw>*
