### ISSUE TITLE
Suggestion: shorten the duration of the menu animation

### ISSUE THREAD

**Issue by vickychijwani** [curiositry/mnml-ghost-theme#36]
Hi, I'm a [long-time MNML user][1] (although haven't updated in a while because of my own customizations). I was looking at the latest version and it looks pretty slick -- I might update to it soon.

I noticed one thing that could perhaps be improved: the animation for the navigation menu feels quite slow and is significantly longer (1 second) than what's [generally recommended][2] (250-500 msec). [Here's some scientific justification][3] for using a shorter duration.

Let me know your thoughts.

[1]: http://vickychijwani.me
[2]: https://material.google.com/motion/duration-easing.html#duration-easing-common-durations
[3]: http://ux.stackexchange.com/q/66604/3587

**Comment by curiositry** [comment]
Thanks Vicky. You have a good point (and good citations :) ). I’ve adjusted the menu transition to half a second. Let me know what you think.

**Comment by vickychijwani** [comment]
Sounds good :+1:
