### ISSUE TITLE
Hamburger Menu Overlapping Title Text On Narrow Screens

### ISSUE THREAD

**Issue by alfiepates** [curiositry/mnml-ghost-theme#40]
I'm opening way too many issues today, aren't I? 

Anyway, see this [twitter thread](https://twitter.com/alfiepates/status/839217978986102785).

Reproducible by opening https://blog.alfiepates.me on a 360px-wide "mobile device" using the Google Chrome developer tools.

**Comment by curiositry** [comment]
Ah, that’s ugly :)

Here’s a quick fix you can pop in your code injection:

```
.page-title {
  padding-right: 50px;
}
```

There shouldn’t be any side effects on large screens, but you could wrap it in a 360px breakpoint to be on the safe side. I’ll put something permanent in place shortly.
