### ISSUE TITLE
No margin-top for headings

### ISSUE THREAD

**Issue by rheicide** [curiositry/mnml-ghost-theme#41]
First of all, thank you @curiositry for this cool theme!

I spotted a style problem with the headings, which I think was caused by changes introduced in Ghost 1.0+.

Here's what a heading looks like in Mnml's demo page:

![screenshot from 2017-08-08 09 23 29](https://user-images.githubusercontent.com/953254/29053780-47a6dba0-7c1c-11e7-84d5-bdfe563ea585.png)

Here's what it looks like in Ghost 1.5:

![screenshot from 2017-08-08 09 24 25](https://user-images.githubusercontent.com/953254/29053925-227ca8f4-7c1d-11e7-8c20-9fa24ca8ab57.png)

Apparently it's because the post content now resides in a `.kg-card-markdown` div:

![selection_010](https://user-images.githubusercontent.com/953254/29053940-3289027e-7c1d-11e7-99b7-6f85fe61c7bb.png)

Which makes the following CSS rule inapplicable:

![selection_011](https://user-images.githubusercontent.com/953254/29054051-e021ef4a-7c1d-11e7-983e-8cd27557875e.png)

**Comment by curiositry** [comment]
@rheicide Thanks for pointing this out, and sorry for the delay getting back to you!

Updated the theme to correct this issue, as well as a few other styling problems caused by addition of `.kg-card.markdown`.

Let me know if you run into any other issues :)

**Comment by rheicide** [comment]
No problem, thanks for the fix @curiositry !
