### ISSUE TITLE
Let me know if I can help :-p

### ISSUE THREAD

**Issue by pascalandy** [curiositry/mnml-ghost-theme#42]
Hi,
I’m the owner of [play-with-ghost](http://play-with-ghost.com/) and one big feature I'm working on is to showcase templates I enjoy like yours. 

Let me know if I can help you by hosting a staging environment of your Ghost project(s) or anything related of the backend of hosting Ghost.

Cheers!
[Pascal](https://twitter.com/askpascalandy/)

**Comment by curiositry** [comment]
Thanks for your message @pascalandy — the answer is yes! I have Ghost LTS hosting, but haven’t found any satisfactory way to host Ghost v1.0 blogs and theme demo sites. Shoot me an email at **info** [AT] **autodidacts** [DOT] **io** and lets talk!

**Comment by pascalandy** [comment]
Very cool, will do!
