### ISSUE TITLE
Change the orange color

### ISSUE THREAD

**Issue by johnhenriksson** [curiositry/mnml-ghost-theme#44]
Hi! Is it supported in some way to change the orange color of the titles and stuff? Is it possible to do some sort of code injection to make it change to lets say black color?

**Comment by curiositry** [comment]
Yes. The simplest would be to run a search and replace through the CSS, replacing all instances "orange" and "#dd4814" with "grey" and "black", or the colours of your choice. 

Another option would be to use the code injection pane of you blog’s admin panel to change the colour certain elements with CSS.
