### ISSUE TITLE
Theme translations

### ISSUE THREAD

**Issue by LechPa** [curiositry/mnml-ghost-theme#45]
I was trying to translate your theme using: https://ghost.org/blog/theme-translations/
but with no effect. I have added all the files described in the guide and I was replacing strings with translation helper {{t "some string"}}
What is missing?

**Comment by curiositry** [comment]
@LechPa You set the locale from your blog’s admin panel to match the translation file, correct?

**Comment by LechPa** [comment]
@curiositry correct. I think it's not a bug - I was running this from Debian (Windows Subsystem for Linux (WSL)) and this could be permissions related... :/
Btw maybe you can add some initial code for translations (e.g. make strings translation-ready)? I think I can do this as pull request if you include this in the main release. What do you think?

**Comment by curiositry** [comment]
@LechPa Great! If you add i18n support and submit a pull request that would be fantastic.

(Adding i18n support does create an additional layer of complexity — needing to update the locale file(s) every time you change label, for example — so I’ve been waiting to add translation support to MNML until there was demand for it.)

**Comment by LechPa** [comment]
Cool, I'll send a pull request in week or two :)

**Comment by PLUYA** [comment]
What happened to the i18n support, @LechPa ? I would like to contribute german translation and greek, if needed. Btw @curiositry thanks for the great work!

**Comment by LechPa** [comment]
@PLUYA @curiositry 
Sorry, I had some issues and it was taking too much time - I'm not using this theme so I will not be able to provide i18n support. Sorry about that.
