### ISSUE TITLE
YouTube widget is shrunk with the latest MNML theme

### ISSUE THREAD

**Issue by lessless** [curiositry/mnml-ghost-theme#47]
Hi,

I’m running the latest MNML (right from the master) on my blog and have a problem with shrunk YouTube video widget https://kurtov.pro/blog/p/c1b229f9-5388-4246-90db-4a60927381fe/

If I manually set `height` and `width` properties on the iframe element in the dev tools then it’s all fine https://imgur.com/rVNxvEM

Is this a problem with a theme and if yes - how do I fix it?

**Comment by curiositry** [comment]
Thank you for bringing this to my attention. @lessless. For some reason I didn't get an email notification for this issue, and only saw it today — sorry. 

I have pushed an update that should fix this issue.

**Comment by lessless** [comment]
It works now,  thanks!
