### ISSUE TITLE
Prism integration - how to fix code blocks size? 

### ISSUE THREAD

**Issue by lessless** [curiositry/mnml-ghost-theme#48]
Hi,

I followed the official tutorial on adding syntax highlight https://ghost.org/docs/tutorials/code-syntax-highlighting/ and installing Prism seems to skew font size in the code blocks 

![difference between font sizes](https://imgur.com/DPRmqmV.png)

If I disable `font-size: 1em;` setting for `code[class*="language-"], pre[class*="language-"]` everything seems to be ok, but I'm not good with CSS at all.

![disabling font-size setting](https://i.imgur.com/DQpA0Kh.jpg)

Can you please help me out with fixing this? 

version:  mnml (mnml-ghost-theme6.0.1)

**Comment by curiositry** [comment]
Hi @lessless. Sorry, for some reason I didn't get a notification for this. When you say "I followed the official tutorial on adding syntax highlight", do you mean that you added Prism with code injection, or just that you followed that tutorial for creating the code blocks? MNML has Prism built in, so there could be a conflict if you added a different version via code injection.

**Comment by lessless** [comment]
@curiositry 

> do you mean that you added Prism with code injection,

yup, that's what I did. 

> MNML has Prism built-in, so there could be a conflict if you added a different version via code injection.


Oh, yeah - removing CSS file injection fixed the problem. The other thing is that I'm trying to get working is code highlighting for Elixir: 

https://kurtov.pro/blog/connecting-to-lightning-network-with-elixir/

I've added 
```
<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.25.0/components/prism-elixir.min.js" integrity="sha512-XdPyCY48VvRU56okVLAGO3+XERM421vhpQXlasbG2FBWL8nqgEkeprNfSG7V70rM6xPE6DQ0DEvLCdXOyngdYA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script> 
```

but it doesn't work by itself, only if I also inject the Prism script before it:

```
<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.25.0/prism.min.js" integrity="sha512-hpZ5pDCF2bRCweL5WoA0/N1elet1KYL5mx3LP555Eg/0ZguaHawxNvEjF6O3rufAChs16HVNhEc6blF/rZoowQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
```


I assume the problem is the order of injection because if I move Prism injection after the elixir plugin file, the highlight doesn't work as well. 

That's must be what's happening with the elixir plugin and a stock Prism script.

**Comment by curiositry** [comment]
@lessless I have updated to Prism 1.25.0 (6ecb7a79bbc2d7467a6520f91fff80e4ee0e1099). Let me know if it helps.
