### ISSUE TITLE
This theme is invalid and cannot be activated

### ISSUE THREAD

**Issue by miip** [curiositry/mnml-ghost-theme#51]
Fatal Errors
Must-fix to activate theme

Replace {{@price.monthly}} and {{@price.yearly}} with {{price monthly_price currency=currency}} and {{price yearly_price currency=currency}} after fetching tier data with {{#get "tiers"}}
There is no longer a global @price object. You need to use {{#get "tiers"}} to fetch all the tiers and get access to the {{price monthly_price currency=currency}} or {{price yearly_price currency=currency}} for each tier
Find more information about the {{price}} helper [here](https://ghost.org/docs/themes/helpers/price/).

Affected files:
members/signup.hbs: {{@price.monthly}} and {{@price.yearly}} should be replaced with {{#get "tiers"}}

**Comment by dvetutnev** [comment]
Confirm.
Ghost version: 5.12.0
![Screenshot from 2022-08-30 22-13-56](https://user-images.githubusercontent.com/7933806/187523867-cffd102f-03b4-4328-ae18-1b81ea7e044e.png)

**Comment by curiositry** [comment]
Thanks for the heads up. Should be fixed in ef6567c560e9b02828f1494264746c38d4848b39.
