### ISSUE TITLE
Consider MathJax instead of KaTeX (or make it selectable)

### ISSUE THREAD

**Issue by horenmar** [curiositry/mnml-ghost-theme#53]
While KaTeX's renderer is very fast, it is also more limited than MathJax's (e.g. no newcommands, generally worse handling of scaling, and last time I tried things like equation labels didn't work either). On my own blog I ended up switching, because KaTeX was not able to render some very math-heavy posts, while MathJax 2.7 took its time but ended up with proper result.

Since MathJax 3 fixes the worst pain points about the previous version (rendering is much faster, there is no longer annoying flickering as the renderer redraws every formula), I think it is worth considering either switching to MathJax, or making it a selectable alternative.

**Comment by curiositry** [comment]
When I last used MathJax, it was quite a headache; but I will take a look at the new version when I get the chance. In the meantime, feel free to create a MathJax partial as an optional alternative, and open a pull request. 

Thanks for your polite, articulate, and helpful issues and pull requests — and sorry for my delay getting to them.
